version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - sqlite-db:/app/sqlite_db
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=src/__init__.py
      - FLASK_ENV=production
    restart: unless-stopped

volumes:
  sqlite-db:
